### ISSUE TITLE
Create a new stack

### ISSUE THREAD

**Issue by FJMentz** [TripleParity/docks-ui#14] opened 2018-04-12 07:28 UTC
Functionality (linked to a button) to add a new stack? If I understand correctly this will basically just be adding multiple containers linked to one stack? 

@devosray can you verify or explain if I went off track?

**Comment by devosray** [comment] 2018-04-12 14:03
Think of it as instead of uploading a Docker file or image tag to be created, you upload a whole Docker-compose file. Here is a really good example: https://docs.docker.com/get-started/part5/#add-a-new-service-and-redeploy

**Comment by FJMentz** [comment] 2018-04-13 05:43
Front-end is paused and just waiting on backend.

**Comment by devosray** [comment] 2018-04-13 06:06
Working on it right now.

**Comment by egeldenhuys** [comment] 2018-06-30 19:52
Duplicate of #114 . Closing this as the new issue has more detail.

**Closed as completed by egeldenhuys** 2018-06-30 19:52 UTC
